# Generated by Django 5.1.2 on 2024-10-23 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post_recipe',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Название рецепта')),
                ('ingredients_list', models.TextField(max_length=300, verbose_name='Количество ингридиентов')),
                ('unit', models.CharField(choices=[('Grams', 'г'), ('Milliliters', 'мл'), ('Pieces', 'шт'), ('Teaspoons', 'ч.л.'), ('Tablespoons', 'ст.л.'), ('Cups', 'чашки'), ('Ounces', 'унц.'), ('Pounds', 'фунты'), ('Slices', 'ломтики'), ('Sprigs', 'веточки'), ('Bunches', 'пучки'), ('Pinches', 'щепотки'), ('Stalks', 'стебли')], max_length=15, verbose_name='Единицы измерения')),
                ('level', models.CharField(choices=[('very_simple', 'Очень просто'), ('simple', 'Просто'), ('medium', 'Средней сложности'), ('hard', 'Сложно'), ('very_hard', 'Очень сложно')], max_length=20, verbose_name='Уровень сложности')),
                ('steps', models.TextField(verbose_name='Шаги приготовления')),
                ('cooking_time', models.DurationField(default=datetime.timedelta(seconds=1800), verbose_name='Время приготовления блюда')),
                ('dish_photo', models.ImageField(blank=True, help_text='Загрузите фото данного блюда.', null=True, upload_to='dish_photos/', verbose_name='Фото блюда')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
