# Generated by Django 5.1.2 on 2024-10-24 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Напишите примерное время приготовления данного блюда. По дефолту:30 min', verbose_name='Время приготовления блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(help_text='Пожалуйста вводите каждый новый ингридиент с новой строки. Индексы проставяться сами', max_length=300, verbose_name='Ингридиенты данного рецепта'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, unique=True, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='steps',
            field=models.TextField(help_text='Пожалуйста вводите каждый новый шаг с новой строки. Индексы проставяться сами', verbose_name='Шаги приготовления'),
        ),
    ]
