# Generated by Django 5.1.2 on 2024-10-29 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0002_alter_post_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='unit',
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Вегетарианское ли блюдо'),
        ),
    ]
