# Generated by Django 5.1.2 on 2024-10-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0002_alter_post_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='unit',
        ),
    ]
