# Generated by Django 5.1.2 on 2024-11-04 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0003_remove_post_recipe_unit_post_recipe_is_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(help_text='Пожалуйста вводите каждый новый ингридиент с новой строки. Индексы проставяться сами', max_length=20000, verbose_name='Ингридиенты данного рецепта'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Вегетарианское ли блюдо?'),
        ),
    ]
