# Generated by Django 5.1.2 on 2024-11-04 16:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0004_alter_post_recipe_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post_recipe',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Напишите примерное время приготовления данного блюда. По умолчанию: 30 мин.', verbose_name='Время приготовления блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(help_text='Пожалуйста, вводите каждый новый ингредиент с новой строки. Индексы проставятся сами.', max_length=20000, verbose_name='Ингредиенты данного рецепта'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='steps',
            field=models.TextField(help_text='Пожалуйста, вводите каждый новый шаг с новой строки. Индексы проставятся сами.', verbose_name='Шаги приготовления'),
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('1 звезда', '1☆'), ('2 звезды', '2☆'), ('3 звезды', '3☆'), ('4 звезды', '4☆'), ('5 звезд', '5☆')], help_text='Оцените данный рецепт', max_length=50, verbose_name='Оценка пользователя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('comments', models.TextField(help_text='Оставьте ваши комментарии', verbose_name='Комментарии')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='RecipeHub.post_recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_at'],
            },
        ),
    ]
