# Generated by Django 5.1.2 on 2024-11-06 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0005_alter_post_recipe_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_recipe',
            name='is_dessert',
            field=models.BooleanField(default=False, verbose_name='Данная еда являетя десертом?'),
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='is_fast_food',
            field=models.BooleanField(default=False, verbose_name='Еда быстрого приготовления?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(max_length=20000, verbose_name='Ингредиенты данного рецепта'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='steps',
            field=models.TextField(verbose_name='Шаги приготовления'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='recipe',
            field=models.ForeignKey(help_text='Выберите рецепт', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='RecipeHub.post_recipe', verbose_name='Рецепт'),
        ),
    ]
