# Generated by Django 5.1.2 on 2024-11-06 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0006_post_recipe_is_dessert_post_recipe_is_fast_food_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='author',
            field=models.CharField(blank=True, help_text='По вашему желанию можете указать автора данного рецепта', max_length=30, unique=True, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_dessert',
            field=models.BooleanField(default=False, help_text='Проставьте галочку если это относится к этой категории', verbose_name='Данная еда являетя десертом?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_fast_food',
            field=models.BooleanField(default=False, help_text='Проставьте галочку если это относится к этой категории', verbose_name='Еда быстрого приготовления?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_vegetarian',
            field=models.BooleanField(default=False, help_text='Проставьте галочку если это относится к этой категории', verbose_name='Вегетарианское ли блюдо?'),
        ),
    ]
