# Generated by Django 5.1.2 on 2024-11-06 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0007_reviews_author_alter_post_recipe_is_dessert_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.CharField(choices=[('Очень просто', 'Очень просто'), ('Просто', 'Просто'), ('Средней сложности', 'Средней сложности'), ('Сложно', 'Сложно'), ('Очень сложно', 'Очень сложно')], max_length=20, verbose_name='Уровень сложности'),
        ),
    ]
