# Generated by Django 5.1.2 on 2024-11-09 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0008_alter_post_recipe_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TeamConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='dish_photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото данного блюда.', null=True, upload_to='static/img/dish_photos/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.CharField(choices=[('1★', '1★'), ('2★', '2★'), ('3★', '3★'), ('4★', '4★'), ('5★', '5★')], help_text='Оцените данный рецепт', max_length=50, verbose_name='Оценка пользователя'),
        ),
    ]
