# Generated by Django 5.1.2 on 2024-11-25 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0009_comments_teamconnection_alter_post_recipe_dish_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.IntegerField(default=datetime.timedelta(seconds=1800), help_text='Напишите примерное время приготовления данного блюда(в минутах)', verbose_name='Время приготовления блюда'),
        ),
    ]
