# Generated by Django 5.1.2 on 2024-11-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0010_likes_alter_post_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='dish_photo',
            field=models.ImageField(blank=True, help_text='Загрузите фото данного блюда.', null=True, upload_to='static/img', verbose_name='Фото блюда'),
        ),
    ]
