# Generated by Django 5.1.2 on 2024-11-26 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0011_alter_post_recipe_dish_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите ваше имя', max_length=20, unique=True, verbose_name='Имя автора профиля')),
                ('profile_photo', models.ImageField(default='static/css/img/profile.png', help_text='Загрузите ваше фото', upload_to='media/profile_photo', verbose_name='Фото профиля')),
                ('country', models.CharField(help_text='Введите вашу страну', max_length=30, verbose_name='Страна')),
                ('city', models.CharField(help_text='Введите ваш город', max_length=30, verbose_name='Город')),
                ('age', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20'), (21, '21'), (22, '22'), (23, '23'), (24, '24'), (25, '25'), (26, '26'), (27, '27'), (28, '28'), (29, '29'), (30, '30'), (31, '31'), (32, '32'), (33, '33'), (34, '34'), (35, '35'), (36, '36'), (37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45'), (46, '46'), (47, '47'), (48, '48'), (49, '49'), (50, '50'), (51, '51'), (52, '52'), (53, '53'), (54, '54'), (55, '55'), (56, '56'), (57, '57'), (58, '58'), (59, '59'), (60, '60'), (61, '61'), (62, '62'), (63, '63'), (64, '64'), (65, '65'), (66, '66'), (67, '67'), (68, '68'), (69, '69'), (70, '70'), (71, '71'), (72, '72'), (73, '73'), (74, '74'), (75, '75'), (76, '76'), (77, '77'), (78, '78'), (79, '79'), (80, '80'), (81, '81'), (82, '82'), (83, '83'), (84, '84'), (85, '85'), (86, '86'), (87, '87'), (88, '88'), (89, '89'), (90, '90'), (91, '91'), (92, '92'), (93, '93'), (94, '94'), (95, '95'), (96, '96'), (97, '97'), (98, '98'), (99, '99'), (100, '100')], help_text='Ваш возраст', verbose_name='Возраст')),
                ('description', models.TextField(help_text='Описание пользователя', max_length=500, verbose_name='Описание')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
        migrations.DeleteModel(
            name='TeamConnection',
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='dish_photo',
            field=models.ImageField(help_text='Загрузите фото данного блюда.', unique=True, upload_to='dish_photos/', verbose_name='Фото блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(max_length=2000, verbose_name='Ингредиенты данного рецепта'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_dessert',
            field=models.BooleanField(help_text='Проставьте галочку если это относится к этой категории', verbose_name='Данная еда являетя десертом?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_fast_food',
            field=models.BooleanField(help_text='Проставьте галочку если это относится к этой категории', verbose_name='Еда быстрого приготовления?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='is_vegetarian',
            field=models.BooleanField(help_text='Проставьте галочку если это относится к этой категории', verbose_name='Вегетарианское ли блюдо?'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='name',
            field=models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название блюда'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(blank=True, help_text='По вашему желанию можете указать автора данного рецепта', max_length=30, verbose_name='Автор'),
        ),
    ]
