# Generated by Django 5.1.2 on 2024-11-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0012_userprofile_delete_comments_delete_likes_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='city',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.CharField(choices=[('Армения', 'Asia/Yerevan'), ('Азербайджан', 'Asia/Baku'), ('Беларусь', 'Europe/Minsk'), ('Казахстан', 'Asia/Almaty'), ('Кыргызстан', 'Asia/Bishkek'), ('Молдова', 'Europe/Chisinau'), ('Россия', 'Russia'), ('Таджикистан', 'Asia/Dushanbe'), ('Туркменистан', 'Asia/Ashgabat'), ('Украина', 'Europe/Kiev'), ('Узбекистан', 'Asia/Tashkent')], help_text='Введите вашу страну', max_length=50, verbose_name='Страна'),
        ),
    ]
