# Generated by Django 5.1.2 on 2024-12-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0013_alter_userprofile_options_remove_userprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at'], 'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
    ]
