# Generated by Django 5.1.2 on 2024-12-03 14:45

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0014_alter_userprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='is_dessert',
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='is_fast_food',
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegetarian', 'Вегетарианское блюдо'), ('fast_food', 'Еда быстрого приготовления'), ('dessert', 'Десерт')], default=['vegetarian', 'fast_food', 'dessert'], help_text='Выберите категории, которые подходят для этого рецепта', max_length=100, verbose_name='Категории блюда'),
        ),
    ]
