# Generated by Django 5.1.2 on 2024-12-04 07:36

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0015_remove_post_recipe_is_dessert_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_recipe',
            name='meal_time',
            field=models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], help_text='Выберите только одно время приёма пищи (завтрак, обед или ужин).', max_length=10, verbose_name='Время приёма пищи'),
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='world_cuisine_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('italian', 'Итальянская кухня'), ('japanese', 'Японская кухня'), ('mexican', 'Мексиканская кухня'), ('chinese', 'Китайская кухня'), ('indian', 'Индийская кухня'), ('french', 'Французская кухня'), ('greek', 'Греческая кухня'), ('arabic', 'Арабская кухня'), ('american', 'Американская кухня')], default=[], help_text="Выберите кухни мира, если выбрана категория 'По кухне мира'", max_length=100, verbose_name='Кухни мира'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='categories',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('vegetarian', 'Вегетарианское блюдо'), ('fast_food', 'Еда быстрого приготовления'), ('dessert', 'Десерт'), ('vegan', 'Веганское'), ('drinks', 'Напитки'), ('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], default=[], help_text='Выберите категории, которые подходят для этого рецепта', max_length=100, verbose_name='Категории блюда'),
        ),
    ]
