# Generated by Django 5.1.2 on 2024-12-06 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0016_post_recipe_meal_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.CharField(choices=[('★', '1★'), ('★★', '2★'), ('★★★', '3★'), ('★★★★', '4★'), ('★★★★★', '5★')], help_text='Оцените данный рецепт', max_length=50, verbose_name='Оценка пользователя'),
        ),
    ]
