# Generated by Django 5.1.2 on 2024-12-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0017_remove_post_recipe_cooking_time_alter_reviews_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.DurationField(default=0),
        ),
    ]
