# Generated by Django 5.1.2 on 2024-12-06 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0017_alter_reviews_grade'),
    ]

    operations = [
    ]
