# Generated by Django 5.1.2 on 2024-12-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0018_insert_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='categories',
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, которые подходят для этого рецепта', related_name='recipes', to='RecipeHub.category', verbose_name='Категории блюда'),
        ),
    ]
