# Generated by Django 5.1.2 on 2024-12-09 15:20

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0019_category_remove_post_recipe_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='world_cuisine_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, default=[], help_text="Выберите кухни мира, если выбрана категория 'По кухне мира'", max_length=100, verbose_name='Кухни мира'),
        ),
    ]
