# Generated by Django 5.1.2 on 2024-12-09 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0020_alter_post_recipe_world_cuisine_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Difficultlevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='meal_time',
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='world_cuisine_categories',
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории, которые подходят для этого рецепта', related_name='recipes', to='RecipeHub.category', verbose_name='Категории блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.difficultlevel', verbose_name='Уровень сложности'),
        ),
    ]
