# Generated by Django 5.1.2 on 2024-12-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0021_difficultlevel_remove_post_recipe_meal_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.TextField(blank=True, default=[], help_text="Укажите уровень сложности. Можете выбрать несколько, разделив их запятыми. Пример: 'Легкий, Средний, Трудный'", verbose_name='Уровень сложности'),
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='meal_time',
            field=models.CharField(blank=True, choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин')], help_text='Выберите только одно время приёма пищи (завтрак, обед или ужин).', max_length=10, verbose_name='Время приёма пищи'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='categories',
            field=models.ManyToManyField(blank=True, help_text='Выберите категории, которые подходят для этого рецепта', related_name='recipes', to='RecipeHub.category', verbose_name='Категории блюда'),
        ),
        migrations.DeleteModel(
            name='Difficultlevel',
        ),
    ]
