# Generated by Django 5.1.2 on 2024-12-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0022_alter_post_recipe_level_post_recipe_meal_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='meal_time',
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.CharField(choices=[('Очень просто', 'Очень просто'), ('Просто', 'Просто'), ('Средней сложности', 'Средней сложности'), ('Сложно', 'Сложно'), ('Очень сложно', 'Очень сложно')], max_length=20, verbose_name='Уровень сложности'),
        ),
    ]
