# Generated by Django 5.1.2 on 2024-12-09 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0023_remove_post_recipe_meal_time_alter_post_recipe_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.difficultylevel', verbose_name='Уровень сложности'),
        ),
    ]
