# Generated by Django 5.1.2 on 2024-12-09 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0024_difficultylevel_alter_post_recipe_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='level',
        ),
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
    ]
