# Generated by Django 5.1.2 on 2024-12-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0026_difficultylevel_post_recipe_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='DifficultyLevel',
        ),
    ]
