# Generated by Django 5.1.2 on 2024-12-10 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0028_difficultylevel_alter_post_recipe_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='reviews',
            name='grade',
            field=models.ForeignKey(help_text='Оцените данный рецепт', on_delete=django.db.models.deletion.CASCADE, to='RecipeHub.grade', verbose_name='Оценка пользователя'),
        ),
    ]
