# Generated by Django 5.1.2 on 2024-12-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0029_grade_alter_reviews_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100, unique=True)),
                ('timezone', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezones',
            },
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(blank=True, help_text='Введите вашу страну', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.timezone', verbose_name='Страна'),
        ),
    ]
