# Generated by Django 5.1.2 on 2024-12-10 17:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0030_timezone_alter_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='Age',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.IntegerField(help_text='Введите возраст', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Age',
                'verbose_name_plural': 'Ages',
            },
        ),
        migrations.AlterField(
            model_name='grade',
            name='value',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.ForeignKey(blank=True, help_text='Ваш возраст', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.age', verbose_name='Возраст'),
        ),
    ]
