# Generated by Django 5.1.2 on 2024-12-12 14:30

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0031_age_alter_grade_value_alter_userprofile_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Кухня мира',
                'verbose_name_plural': 'Кухни мира',
            },
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.IntegerField(default=datetime.timedelta(seconds=1800), help_text='Напишите примерное время приготовления данного блюда(в минутах)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Время приготовления блюда'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='author',
            field=models.CharField(max_length=30, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='cuisines',
            field=models.ManyToManyField(blank=True, help_text='Выберите кухни мира для этого рецепта', related_name='recipes', to='RecipeHub.cuisine', verbose_name='Кухни мира'),
        ),
    ]
