# Generated by Django 5.1.2 on 2024-12-13 14:21

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0032_cuisine_alter_post_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post_recipe',
            managers=[
                ('recipe_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
