# Generated by Django 5.1.2 on 2024-12-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0033_alter_post_recipe_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='post_recipe',
            name='average_grade',
            field=models.FloatField(default=0, help_text='Средняя оценка этого рецепта по отзывам', verbose_name='Средняя оценка'),
        ),
    ]
