# Generated by Django 5.1.2 on 2024-12-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0034_post_recipe_average_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='average_grade',
        ),
    ]
