# Generated by Django 5.1.2 on 2024-12-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0035_remove_post_recipe_average_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.difficultylevel', verbose_name='Уровень сложности'),
        ),
    ]
