# Generated by Django 5.1.2 on 2024-12-20 06:31

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0037_teamconnection_userprofile_user_alter_category_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название ингредиента')),
            ],
        ),
        migrations.AlterModelManagers(
            name='post_recipe',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='userprofile',
            managers=[
                ('profiles', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='post_recipe',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.ManyToManyField(related_name='recipes', to='RecipeHub.ingredient', verbose_name='Ингредиенты'),
        ),
    ]
