# Generated by Django 5.1.2 on 2024-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0038_ingredient_alter_post_recipe_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post_recipe',
            name='ingredients_list',
        ),
        migrations.AddField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(default=0, max_length=1500, verbose_name='Ингредиенты'),
        ),
    ]
