# Generated by Django 5.1.2 on 2024-12-20 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0039_remove_post_recipe_ingredients_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(max_length=1500, verbose_name='Ингредиенты'),
        ),
    ]
