# Generated by Django 5.1.2 on 2024-12-20 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0040_alter_post_recipe_ingredients_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(blank=True, max_length=1500, verbose_name='Ингредиенты'),
        ),
    ]
