# Generated by Django 5.1.2 on 2025-01-03 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0042_alter_post_recipe_ingredients_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CookingTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField(default=0, help_text='Количество дней, если время превышает один день', verbose_name='Дни')),
                ('hours', models.PositiveIntegerField(default=0, help_text='Количество часов', verbose_name='Часы')),
                ('minutes', models.PositiveIntegerField(default=0, help_text='Количество минут', verbose_name='Минуты')),
                ('seconds', models.PositiveIntegerField(default=0, help_text='Количество секунд', verbose_name='Секунды')),
            ],
        ),
        migrations.CreateModel(
            name='Likes_recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Likes_reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='categories',
            field=models.ManyToManyField(help_text='Выберите категории, которые подходят для этого рецепта', related_name='recipes', to='RecipeHub.category', verbose_name='Категории блюда'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cuisines',
            field=models.ManyToManyField(help_text='Выберите кухни мира для этого рецепта', related_name='recipes', to='RecipeHub.cuisine', verbose_name='Кухни мира'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='ingredients_list',
            field=models.TextField(max_length=1500, verbose_name='Ингредиенты'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.difficultylevel', verbose_name='Уровень сложности'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='age',
            field=models.ForeignKey(help_text='Ваш возраст', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.age', verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='country',
            field=models.ForeignKey(help_text='Введите вашу страну', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.timezone', verbose_name='Страна'),
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.ForeignKey(help_text='Введите время приготовления блюда в днях, часах, минутах и секундах.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='RecipeHub.cookingtime', verbose_name='Время приготовления блюда'),
        ),
    ]
