# Generated by Django 5.1.2 on 2025-01-06 14:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeHub', '0043_comments_cookingtime_likes_recipes_likes_reviews_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Likes_reviews',
            new_name='RecipeLikes',
        ),
        migrations.RenameModel(
            old_name='Likes_recipes',
            new_name='ReviewLikes',
        ),
        migrations.AlterField(
            model_name='post_recipe',
            name='cooking_time',
            field=models.DurationField(default=datetime.timedelta(seconds=1800), help_text='Напишите примерное время приготовления данного блюда (в днях, часах, минутах, секундах)', verbose_name='Время приготовления блюда'),
        ),
        migrations.DeleteModel(
            name='CookingTime',
        ),
    ]
